/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as CarrinhoRouteImport } from './routes/carrinho'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PagamentoRouteImport } from './routes/pagamento'
import { Route as NftNftIdRouteImport } from './routes/nft.$nftId'
import { Route as PedidoOrderIdRouteImport } from './routes/pedido.$orderId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const CarrinhoRoute = CarrinhoRouteImport.update({
  id: '/carrinho',
  path: '/carrinho',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PagamentoRoute = PagamentoRouteImport.update({
  id: '/pagamento',
  path: '/pagamento',
  getParentRoute: () => rootRouteImport,
} as any)
const NftNftIdRoute = NftNftIdRouteImport.update({
  id: '/nft/$nftId',
  path: '/nft/$nftId',
  getParentRoute: () => rootRouteImport,
} as any)
const PedidoOrderIdRoute = PedidoOrderIdRouteImport.update({
  id: '/pedido/$orderId',
  path: '/pedido/$orderId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/cadastro': typeof CadastroRoute
  '/carrinho': typeof CarrinhoRoute
  '/login': typeof LoginRoute
  '/pagamento': typeof PagamentoRoute
  '/nft/$nftId': typeof NftNftIdRoute
  '/pedido/$orderId': typeof PedidoOrderIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/pagamento'
    | '/nft/$nftId'
    | '/pedido/$orderId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/pagamento'
    | '/nft/$nftId'
    | '/pedido/$orderId'
  id:
    | '__root__'
    | '/'
    | '/cadastro'
    | '/carrinho'
    | '/login'
    | '/pagamento'
    | '/nft/$nftId'
    | '/pedido/$orderId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  CadastroRoute: typeof CadastroRoute
  CarrinhoRoute: typeof CarrinhoRoute
  LoginRoute: typeof LoginRoute
  PagamentoRoute: typeof PagamentoRoute
  NftNftIdRoute: typeof NftNftIdRoute
  PedidoOrderIdRoute: typeof PedidoOrderIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/carrinho': {
      id: '/carrinho'
      path: '/carrinho'
      fullPath: '/carrinho'
      preLoaderRoute: typeof CarrinhoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pagamento': {
      id: '/pagamento'
      path: '/pagamento'
      fullPath: '/pagamento'
      preLoaderRoute: typeof PagamentoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/nft/$nftId': {
      id: '/nft/$nftId'
      path: '/nft/$nftId'
      fullPath: '/nft/$nftId'
      preLoaderRoute: typeof NftNftIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/pedido/$orderId': {
      id: '/pedido/$orderId'
      path: '/pedido/$orderId'
      fullPath: '/pedido/$orderId'
      preLoaderRoute: typeof PedidoOrderIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  CadastroRoute: CadastroRoute,
  CarrinhoRoute: CarrinhoRoute,
  LoginRoute: LoginRoute,
  PagamentoRoute: PagamentoRoute,
  NftNftIdRoute: NftNftIdRoute,
  PedidoOrderIdRoute: PedidoOrderIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
